Feature: H) Prepare block in evaluation reports (slice-03)

  Every evaluation report generated by /career-ops oferta or auto-pipeline
  must include a ## H) Prepare section containing a ready-to-run
  rusty_cv_creator insert command. The block is generated unconditionally —
  there is no score gate (D-13). Invocation is manual (D-22).

  Scenarios that test block CONTENT read modes/oferta.md (the template) directly;
  they do not require a live Claude session. Scenarios that test a generated report
  are tagged @requires_external.

  Background:
    Given the career-ops repository is at the project root

  # ─── WALKING SKELETON ────────────────────────────────────────────────────────

  @walking_skeleton @driving_port @real-io @US-3 @requires_external
  Scenario: Evaluation report always includes H) Prepare block
    # Driving port: /career-ops oferta — Claude Code skill (manual smoke)
    # This is the end-to-end proof. Verified by the maintainer post-delivery.
    Given a job description URL for a software role at any company
    And the career-ops evaluation mode is active (oferta or auto-pipeline)
    When the evaluation is complete and the report is written to reports/
    Then the report contains "## H) Prepare"
    And the report contains a rusty_cv_creator insert command
    And the report contains "--job-title" populated with the extracted job title
    And the report contains "--company-name" populated with the extracted company name
    And the report contains "--quote" populated with a sentence of at most 120 characters

  # ─── TEMPLATE CONTENT (no live Claude needed) ────────────────────────────────

  @real-io @US-3
  Scenario: oferta.md template contains the H) Prepare block spec
    # Tests the source of truth — the template — not a generated report.
    # If the template is correct, all generated reports will be correct.
    Given modes/oferta.md exists
    When I read the "## H) Prepare" section in modes/oferta.md
    Then the template contains "rusty_cv_creator insert"
    And the template contains "--job-title"
    And the template contains "--company-name"
    And the template contains "--quote"

  @real-io @US-3
  Scenario: H) Prepare block in oferta.md carries manual-invocation label
    # AC4 (strengthened per addendum A3): block must explicitly state
    # "Copy-paste to generate your CV" and that career-ops does not call
    # rusty_cv_creator automatically. D-22 is a deliberate design decision.
    Given modes/oferta.md exists
    When I read the "## H) Prepare" section in modes/oferta.md
    Then the template contains "Copy-paste to generate your CV"
    And the template contains "Invocation is manual"
    And the template contains "career-ops does not"

  @real-io @US-3
  Scenario: H) Prepare block in oferta.md documents B-CV-01 quote injection gap
    # AC3b: block must note that --quote is accepted but quote injection is
    # currently inactive in rusty_cv_creator (D-23, out of scope here).
    Given modes/oferta.md exists
    When I read the "## H) Prepare" section in modes/oferta.md
    Then the template contains "_change_quote_in_destination_cv"
    And the template notes that quote injection is currently inactive

  @real-io @US-3 @boundary
  Scenario: oferta.md H) Prepare section has no score-gate condition
    # D-13: the prepare block is generated unconditionally.
    # Test: no "if score" or "score >= " or threshold condition around H section.
    Given modes/oferta.md exists
    When I read modes/oferta.md
    Then the "## H) Prepare" section is not wrapped in a score threshold condition
    And no text near "## H) Prepare" references a minimum score requirement

  # ─── TEST-SUITE VERIFICATION ─────────────────────────────────────────────────

  @real-io @US-3
  Scenario: test-all.mjs checks H) Prepare presence in all existing reports
    # Story 3 AC5: the test suite enforces the H) Prepare invariant
    # on any report already on disk — not just on freshly generated ones.
    # If reports/ is absent or empty, the check warns and proceeds.
    Given at least one report file exists in reports/
    When I run "node test-all.mjs" from the project root
    Then the test suite checks each report file for "## H) Prepare"
    And the check passes when every report contains the block
    And the check fails with a descriptive message when any report is missing the block
